spring:
  application:
    name: MoMeet
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  cloud:
    aws:
      credentials:
        access-key: ${AWS_IAM_ACCESS_KEY}
        secret-key: ${AWS_IAM_SECRET_KEY}
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}
      region:
        static: ap-northeast-2
  mail:
    host: ${BREVO_STMP_HOST}
    port: ${BREVO_STMP_PORT}
    username: ${BREVO_USERNAME}
    password: ${BREVO_PASSWORD}
    from-domain: ${EMAIL_FROM_DOMAIN}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:sql/init_scheme.sql, classpath:sql/init_data.sql

app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      access-token:
        expiration_in_second: 3600
      refresh-token:
        expiration_in_second: 604800
      ws-upgrade-token:
        expiration_in_second: 30 # 30초
      issuer: momeet

    https:
       enabled: false
       domain: localhost:8080

    websocket:
      endpoint: /ws/chat
      handshake-header: token

    cors:
      allowed-origins:
        - http://localhost:*
        - http://127.0.0.1:*

    whitelist-urls:
      - /api/auth/login
      - /api/auth/signup
      - /api/auth/refresh
      - /api/auth/verify
      - /api/auth/kakao
      - /api/auth/kakao/callback
      - /api/auth/kakao/withdraw
      - /error
      - /admin
      - /admin/**
      - /health

logging:
  level:
    root: INFO
    com.pnu.momeet: DEBUG
  file:
    path: './logs'

ip-hash:
  secret-key: ${IP_HASH_SECRET_KEY:default-secret}
  method: SHA-256

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  admin-key: ${KAKAO_ADMIN_KEY}
  redirect-uri: http://localhost:8080/api/auth/kakao/callback
  token-url: https://kauth.kakao.com/oauth/token
  user-info-url: https://kapi.kakao.com/v2/user/me
  unlink-url: https://kapi.kakao.com/v1/user/unlink

momeet:
  temperature:
    bayesian:
      prior-k: 5.0

frontend:
  url: https://${FRONTEND_DOMAIN_NAME:localhost:3000}
