spring:
  application:
    name: MoMeet
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  cloud:
    aws:
      credentials:
        access-key: ${AWS_IAM_ACCESS_KEY}
        secret-key: ${AWS_IAM_SECRET_KEY}
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}
      region:
        static: ap-northeast-2

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:sql/init_scheme.sql, classpath:sql/init_data.sql

app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      access-token:
        name_in_cookie: access_token
        expiration_in_second: 3600
      refresh-token:
        name_in_cookie: refresh_token
        expiration_in_second: 604800
      issuer: momeet

    https:
       enabled: false
       domain: localhost:8080
       allow-origins:
         - http://localhost:*
         - http://127.0.0.1:*

    whitelist-urls:
      - /api/auth/login
      - /api/auth/signup
      - /api/auth/refresh
      - /api/auth/kakao
      - /api/auth/kakao/callback
      - /api/auth/kakao/withdraw
      - /error
      - /admin
      - /admin/**
      - /ws/**
      - /ws/chat/**
      - /health

logging:
  level:
    root: INFO
    com.pnu.momeet: DEBUG
  file:
    path: './logs'

ip-hash:
  secret-key: ${IP_HASH_SECRET_KEY:default-secret}
  method: SHA-256

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  admin-key: ${KAKAO_ADMIN_KEY}
  redirect-uri: http://localhost:8080/api/auth/kakao/callback
  token-url: https://kauth.kakao.com/oauth/token
  user-info-url: https://kapi.kakao.com/v2/user/me
  unlink-url: https://kapi.kakao.com/v1/user/unlink

momeet:
  temperature:
    bayesian:
      prior-k: 5.0