spring:
  application:
    name: MoMeet

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:sql/init_scheme.sql, classpath:sql/init_data.sql

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration: 3600
  refresh-token:
    expiration: 604800
  issuer: momeet
