spring:
  jpa:
    show-sql: false
app:
  security:
    https:
      enabled: true
      domain: ${PROD_DOMAIN_NAME}
    cors:
      allowed-origins:
        - http://${FRONTEND_DOMAIN_NAME} # 프론트엔드 도메인 허용
        - https://${FRONTEND_DOMAIN_NAME}
        - https://${PROD_DOMAIN_NAME} # api 서브도메인 허용


logging:
  level:
    root: WARN
    com.pnu.momeet: INFO
  file:
    path: './logs'
kakao:
  redirect-uri: https://${PROD_DOMAIN_NAME}/api/auth/kakao/callback

server:
  address: 0.0.0.0