spring:
  application:
    name: MoMeet
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:sql/init_scheme.sql, classpath:sql/init_data.sql

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration: ${ACCESS_TOKEN_EXPIRATION_SECONDS}
  refresh-token:
    expiration: ${REFRESH_TOKEN_EXPIRATION_SECONDS}
  issuer: ${JWT_ISSUER}

cloud:
  aws:
    credentials:
      access-key: ${AWS_IAM_ACCESS_KEY}
      secret-key: ${AWS_IAM_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    region:
      static: ap-northeast-2