spring:
  jpa:
    show-sql: false
app:
  security:
    https:
      enabled: true
      domain: ${PROD_DOMAIN_NAME}
    cors:
      allowed-origins:
        - http://localhost:* # 아직 개발 단계이므로 테스팅을 위해 로컬호스트 허용
        - http://127.0.0.1:*
        - http://${FRONTEND_DOMAIN_NAME} # 프론트엔드 도메인 허용
        - https://${FRONTEND_DOMAIN_NAME}
        - https://${PROD_DOMAIN_NAME} # api 서브도메인 허용


logging:
  level:
    root: WARN
    com.pnu.momeet: DEBUG
  file:
    path: './logs'
kakao:
  redirect-uri: https://${PROD_DOMAIN_NAME}/api/auth/kakao/callback

server:
  address: 0.0.0.0