spring:
  application:
    name: MoMeet
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

  cloud:
    aws:
      credentials:
        access-key: ${AWS_IAM_ACCESS_KEY}
        secret-key: ${AWS_IAM_SECRET_KEY}
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}
      region:
        static: ap-northeast-2

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:sql/init_scheme.sql, classpath:sql/init_data.sql

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration: 3600
  refresh-token:
    expiration: 604800
  issuer: momeet