FROM postgres:17

COPY ./sql/korean_spatial.sql /docker-entrypoint-initdb.d/01_korean_spatial.sql
COPY ./sql/sigungu_scheme.sql /docker-entrypoint-initdb.d/02_sigungu_scheme.sql
COPY ./sql/sigungu_data.sql /docker-entrypoint-initdb.d/03_sigungu_data.sql

RUN chmod a+r /docker-entrypoint-initdb.d/*.sql


RUN apt-get update \
    && apt-get install -y postgis postgresql-17-postgis \
    && rm -rf /var/lib/apt/lists/*

ENV POSTGRES_DB=postgres
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_PORT=5432